name: CI/CD
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          npm install
      - name: Build
        run: npm run compile
      - name: Run tests
        run: xvfb-run -a npm test
      - name: Package and Publish
        if: success() && startsWith(github.ref, 'refs/tags/')
        run: |
          npm run compile
          npm run vscode:prepublish
          npx vsce publish -p ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
        env:
          VSCODE_MARKETPLACE_TOKEN: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
