name: CI/CD

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '22'
      - run: npm install
      - run: npm run test
      - name: Publish to VS Code Marketplace
        if: success() && startsWith(github.ref, 'refs/tags/')
        run: npx vsce publish -p ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
        env:
          VSCODE_MARKETPLACE_TOKEN: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
